// Fonction pour nettoyer les textes : retire accents, tirets, espaces superflus, passe en minuscules
function nettoyerTexte(str) {
  return str
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "") // supprime accents
    .replace(/-/g, "")                                // supprime tirets
    .replace(/\s+/g, "")                              // supprime espaces
    .toLowerCase()                                    // passe en minuscules
    .trim();                                          // supprime débuts/fins blancs
}

// Liste complète des passagers
const passagers = [
  { nom: "POINÇON", prenom: "Alexandre", siege: "25E" },
{ nom: "VERDREL", prenom: "Alexandre", siege: "20R" },
{ nom: "KALINICHENKO", prenom: "Alina", siege: "28S" },
{ nom: "CUROT", prenom: "Amélie", siege: "28E" },
{ nom: "LEPRINCE", prenom: "Amélie", siege: "25D" },
{ nom: "BIVILLE", prenom: "Anita", siege: "17A" },
{ nom: "MAUGERE", prenom: "Anne", siege: "5S" },
{ nom: "DECELIER", prenom: "Annick", siege: "17S" },
{ nom: "TAMARELLE", prenom: "Antoine", siege: "27F" },
{ nom: "COTTENCEAU", prenom: "Apolline", siege: "25C" },
{ nom: "ETAY", prenom: "Apolline", siege: "25E" },
{ nom: "NAJIB", prenom: "Arsalan", siege: "27E" },
{ nom: "DUTOT", prenom: "Aurélie", siege: "10A" },
{ nom: "COTTENCEAU", prenom: "Aurélien", siege: "1A" },
{ nom: "ALLEAUME", prenom: "Auriane", siege: "20E" },
{ nom: "LOUIS", prenom: "Baptiste", siege: "25L" },
{ nom: "WAZZAU", prenom: "Béatrice", siege: "25L" },
{ nom: "COTTENCEAU", prenom: "Benoît", siege: "17P" },
{ nom: "GALLOO", prenom: "Blanche", siege: "25O" },
{ nom: "ALEMPIJEVIC", prenom: "Charlotte", siege: "4S" },
{ nom: "CHANDELIER", prenom: "Christian", siege: "8O" },
{ nom: "BOTTOIS", prenom: "Christine", siege: "8R" },
{ nom: "BRUYAT", prenom: "Christophe", siege: "2S" },
{ nom: "MAUGARD", prenom: "Christophe", siege: "6G" },
{ nom: "COTTENCEAU", prenom: "Claire", siege: "1N" },
{ nom: "BOTTOIS", prenom: "Clément", siege: "7E" },
{ nom: "LEBRETON", prenom: "Clément", siege: "2A" },
{ nom: "PELERINS", prenom: "Clément", siege: "5U" },
{ nom: "MORISSE", prenom: "Colin", siege: "25A" },
{ nom: "TAMARELLE", prenom: "Coraline", siege: "20C" },
{ nom: "CHARREAU", prenom: "Corinne", siege: "6A" },
{ nom: "BECHEREL", prenom: "Cyprien", siege: "5R" },
{ nom: "RABOURDIN", prenom: "Damien", siege: "20N" },
{ nom: "LE NAGARD", prenom: "David", siege: "10E" },
{ nom: "DUTOT", prenom: "Didier", siege: "5O" },
{ nom: "WAZZAU", prenom: "Dominique", siege: "22E" },
{ nom: "RABOURDIN", prenom: "Elodie", siege: "20I" },
{ nom: "SABOURIN", prenom: "Emma", siege: "8A" },
{ nom: "POMMIER", prenom: "Emmanuel", siege: "5I" },
{ nom: "POSTIC", prenom: "Erwan", siege: "27A" },
{ nom: "COTTENCEAU", prenom: "Erwann", siege: "16E" },
{ nom: "BERTIN", prenom: "Estelle", siege: "3E" },
{ nom: "COTTENCEAU", prenom: "Fabienne", siege: "22S" },
{ nom: "DAMMAK", prenom: "Firas", siege: "3A" },
{ nom: "LEROUX", prenom: "Flore", siege: "10M" },
{ nom: "DE RIVIERE", prenom: "François", siege: "2E" },
{ nom: "SOURICE", prenom: "François-Xavier", siege: "19O" },
{ nom: "LEMASSON", prenom: "Françoise", siege: "19E" },
{ nom: "DEVANNE", prenom: "Frédéric", siege: "1A" },
{ nom: "POSTIC", prenom: "Geneviève", siege: "27N" },
{ nom: "DUTOT", prenom: "Guillaume ", siege: "8T" },
{ nom: "DE RIVIERE", prenom: "Gwénola", siege: "19C" },
{ nom: "MICHEL", prenom: "Ingrid", siege: "4A" },
{ nom: "BRUYAT", prenom: "Isabelle", siege: "19I" },
{ nom: "VASSEUR", prenom: "Jean ", siege: "27S" },
{ nom: "BERTIN", prenom: "Jean-Luc", siege: "3M" },
{ nom: "CAILLOU", prenom: "Jenny", siege: "20E" },
{ nom: "MONNIER", prenom: "Jérémy", siege: "10P" },
{ nom: "COURTIN", prenom: "Jérôme", siege: "4L" },
{ nom: "COCAGNE", prenom: "Joëlle", siege: "5N" },
{ nom: "LEFRANC", prenom: "Jordan", siege: "3G" },
{ nom: "COTTENCEAU", prenom: "Josiane", siege: "1L" },
{ nom: "RABL", prenom: "Jules", siege: "6B" },
{ nom: "DEVANNE", prenom: "Julie", siege: "6S" },
{ nom: "DECORPS", prenom: "Julien", siege: "1S" },
{ nom: "MILLIARD", prenom: "Julien", siege: "17P" },
{ nom: "DANIEL", prenom: "Justine", siege: "17O" },
{ nom: "MASURE", prenom: "Karine", siege: "4I" },
{ nom: "PIMONT", prenom: "Karine", siege: "2A" },
{ nom: "ZIMMERMANNOVA", prenom: "Kristyna", siege: "1L" },
{ nom: "DUFEUTRELLE", prenom: "Lauranne", siege: "27T" },
{ nom: "DENICOU", prenom: "Laure", siege: "6A" },
{ nom: "POMMIER", prenom: "Laurence", siege: "10I" },
{ nom: "MORLAY", prenom: "Laurent", siege: "19E" },
{ nom: "BERNSTEIN", prenom: "Léa", siege: "10R" },
{ nom: "MOREUL", prenom: "Léina", siege: "7R" },
{ nom: "SAADI", prenom: "Linda", siege: "7I" },
{ nom: "DORE", prenom: "Lise", siege: "22H" },
{ nom: "GILLET", prenom: "Louis", siege: "7S" },
{ nom: "DELESTRE", prenom: "Louis-Charles", siege: "8P" },
{ nom: "TEIXEIRA", prenom: "Lucie", siege: "4E" },
{ nom: "BIVILLE", prenom: "Manon", siege: "7T" },
{ nom: "LAROCHE", prenom: "Manon", siege: "2P" },
{ nom: "LAVOUE", prenom: "Manon", siege: "20E" },
{ nom: "LEFRANCOIS", prenom: "Manon", siege: "17T" },
{ nom: "NANDJI", prenom: "Marie", siege: "1I" },
{ nom: "CHAILLOT", prenom: "Marie Noelle", siege: "22O" },
{ nom: "CHERON", prenom: "Marine", siege: "20M" },
{ nom: "BACHELET", prenom: "Marion", siege: "20O" },
{ nom: "LE NAGARD", prenom: "Maryon", siege: "28J" },
{ nom: "LEBRETON", prenom: "Mathilde", siege: "19M" },
{ nom: "COTTENCEAU", prenom: "Matthieu", siege: "27R" },
{ nom: "PATRY", prenom: "Matthieu", siege: "3E" },
{ nom: "BERTIN", prenom: "Maxime", siege: "27R" },
{ nom: "VAULTIER", prenom: "Maxime", siege: "3N" },
{ nom: "COTTENCEAU", prenom: "Mélanie", siege: "8O" },
{ nom: "DELAUNE", prenom: "Mickael", siege: "28O" },
{ nom: "DEMEYER", prenom: "Mickael ", siege: "7U" },
{ nom: "DEVANNE", prenom: "Monique", siege: "7T" },
{ nom: "RAKIC", prenom: "Natacha", siege: "8E" },
{ nom: "LEPRINCE", prenom: "Nico", siege: "3E" },
{ nom: "GIESE", prenom: "Nicolas", siege: "19E" },
{ nom: "LE NAGARD", prenom: "Nicolas", siege: "16A" },
{ nom: "COTTENCEAU", prenom: "Olivier", siege: "28U" },
{ nom: "HARDY", prenom: "Pascal", siege: "10L" },
{ nom: "HARDY", prenom: "Pascale", siege: "25G" },
{ nom: "PELERINS", prenom: "Paulo", siege: "3T" },
{ nom: "MILCENT", prenom: "Perrine", siege: "27T" },
{ nom: "CHAILLOT", prenom: "Philippe", siege: "22T" },
{ nom: "CHARREAU", prenom: "Philippe", siege: "1C" },
{ nom: "JOUEN", prenom: "Philippe", siege: "3N" },
{ nom: "BOTTOIS", prenom: "Pierre-Olivier", siege: "16S" },
{ nom: "LETOUQ", prenom: "Raynald", siege: "22S" },
{ nom: "GUILLERM", prenom: "Richard", siege: "4V" },
{ nom: "DEVANNE", prenom: "Roger", siege: "28R" },
{ nom: "LEROUX", prenom: "Romain", siege: "16L" },
{ nom: "URVOIS", prenom: "Romain", siege: "5E" },
{ nom: "GALLOO", prenom: "Sarah", siege: "17S" },
{ nom: "MOREUL", prenom: "Sébastien ", siege: "22E" },
{ nom: "COTTENCEAU", prenom: "Séverine", siege: "7O" },
{ nom: "DECORPS", prenom: "Soline", siege: "5X" },
{ nom: "COTTENCEAU", prenom: "Sophie", siege: "6G" },
{ nom: "MASURE", prenom: "Stéphane", siege: "2S" },
{ nom: "MICHEL", prenom: "Sylvain", siege: "19N" },
{ nom: "GUILLERM", prenom: "Sylvie", siege: "19R" },
{ nom: "OURDAS", prenom: "Théophile", siege: "17R" },
{ nom: "BIVILLE", prenom: "Thierry", siege: "3G" },
{ nom: "ALEMPIJEVIC", prenom: "Thomas", siege: "2R" },
{ nom: "COTTENCEAU", prenom: "Timothée", siege: "16E" },
{ nom: "COTTENCEAU", prenom: "Valentin", siege: "5C" },
{ nom: "MAUGARD", prenom: "Valérie", siege: "1E" },
{ nom: "SOURICE", prenom: "Valérie", siege: "2S" },
{ nom: "VASSEUR", prenom: "Valérie", siege: "17E" },
{ nom: "COQUELIN", prenom: "Véronique", siege: "16C" },
{ nom: "LEPELLETIER", prenom: "Véronique", siege: "2G" },
{ nom: "LEMASSON", prenom: "Vincent", siege: "4S" },
{ nom: "LOUIS", prenom: "Wala", siege: "8R" },
{ nom: "MAUGERE", prenom: "Yannick", siege: "10S" },
{ nom: "COTTENCEAU", prenom: "Yves", siege: "6E" }
];

// Fonction pour retrouver un passager à partir d’un nom et prénom saisis
function trouverPassager(nomSaisi, prenomSaisi) {
  const nomNettoye = nettoyerTexte(nomSaisi);
  const prenomNettoye = nettoyerTexte(prenomSaisi);

  return passagers.find(p =>
    nettoyerTexte(p.nom) === nomNettoye &&
    nettoyerTexte(p.prenom) === prenomNettoye
  );
}
